-- Cycle #170-C3: frontend error telemetry sink.
-- Stores sanitized JS/WASM runtime errors reported by the Mini App.
-- Privacy-first: telegram_id is nullable and currently left empty because
-- the endpoint is intentionally unauthenticated (errors may happen before
-- login). No initData tokens are persisted.
CREATE TABLE IF NOT EXISTS client_error_logs (
    id              BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    source          VARCHAR(20) NOT NULL DEFAULT 'unknown',
    message_hash    VARCHAR(64) NOT NULL,
    message         TEXT NOT NULL,
    stack           TEXT,
    url_path        VARCHAR(500),
    user_agent      VARCHAR(500),
    telegram_id     BIGINT,
    occurred_at     TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT client_error_logs_source CHECK (source IN ('wasm','android','ios','unknown'))
);

CREATE INDEX IF NOT EXISTS idx_client_error_logs_hash ON client_error_logs(message_hash);
CREATE INDEX IF NOT EXISTS idx_client_error_logs_occurred_at ON client_error_logs(occurred_at DESC);
