// UI Component Library — woody-weed-bot
// Auto-generated by design system expansion (feat/design-system)

// ---------------------------------------------------------------------------
// Original components
// ---------------------------------------------------------------------------
pub mod bottom_nav;
pub mod button;
pub mod card;
pub mod modal;

pub mod input;
pub mod loading;
pub mod strain_card;
pub mod cart_item;
pub mod strain_grid;
pub mod plant_cell;

// ---------------------------------------------------------------------------
// New design-system components (feat/design-system)
// ---------------------------------------------------------------------------
pub mod badge;
pub mod toast;
pub mod empty_state;
pub mod skeleton;
pub mod progress_bar;
pub mod chip;
pub mod rarity_glow;
pub mod lazy_screen;

// ---------------------------------------------------------------------------
// Re-exports — original
// ---------------------------------------------------------------------------
pub use button::{Button, ButtonProps, ButtonVariant, ButtonSize};
pub use card::{Card, CardProps, CardVariant};
pub use modal::{Modal, ModalProps, ModalSize};
pub use input::{Input, InputProps, InputType};
pub use loading::{Loading, LoadingOverlay, LoadingProps, LoadingSize};
pub use strain_card::{StrainCard, StrainCardProps};
pub use cart_item::{CartItemComponent, CartItemProps};
pub use strain_grid::{StrainGrid, StrainGridProps};
pub use plant_cell::{PlantCell, EmptyPlotCell};

// ---------------------------------------------------------------------------
// Re-exports — new design-system components
// ---------------------------------------------------------------------------
pub use badge::{Badge, BadgeProps, BadgeVariant, BadgeSize};
pub use toast::{Toast, ToastProps, ToastKind, ToastContainer, ToastContainerProps};
pub use empty_state::{EmptyState, EmptyStateProps};
pub use skeleton::{Skeleton, SkeletonProps, SkeletonShape, SkeletonRow, SkeletonRowProps};
pub use progress_bar::{ProgressBar, ProgressBarProps, ProgressColor, ProgressSize};
pub use chip::{Chip, ChipProps, ChipColor, ChipGroup, ChipGroupProps};
pub use rarity_glow::{RarityGlow, RarityGlowProps, Rarity};
pub use lazy_screen::LazyScreen;

// Re-export types from state for convenience
pub use crate::ui::state::CartItem as CartItemType;
