// UI Component Library — woody-weed-bot
// Auto-generated by design system expansion (feat/design-system)

// ---------------------------------------------------------------------------
// Original components
// ---------------------------------------------------------------------------
pub mod bottom_nav;
pub mod button;
pub mod card;
pub mod card_media;
pub mod modal;

pub mod cart_item;
pub mod image_lightbox;
pub mod input;
pub mod loading;
pub mod plant_cell;
pub mod product_detail_modal;
pub mod set_card;
pub mod strain_card;
pub mod strain_grid;
pub mod video_modal;

// ---------------------------------------------------------------------------
// New design-system components (feat/design-system)
// ---------------------------------------------------------------------------
pub mod badge;
pub mod chip;
pub mod empty_state;
pub mod error_banner;
pub mod error_overlay;
pub mod id_picker;
pub mod lazy_screen;
pub mod progress_bar;
pub mod rarity_glow;
pub mod skeleton;
pub mod toast;

// ---------------------------------------------------------------------------
// Re-exports — original
// ---------------------------------------------------------------------------
pub use button::{Button, ButtonProps, ButtonSize, ButtonVariant};
pub use card::{Card, CardProps, CardVariant};
pub use card_media::CardMedia;
pub use cart_item::{CartItemComponent, CartItemProps};
pub use image_lightbox::{ImageLightbox, ImageLightboxProps};
pub use input::{Input, InputProps, InputType};
pub use loading::{Loading, LoadingOverlay, LoadingProps, LoadingSize};
pub use modal::{Modal, ModalProps, ModalSize};
pub use plant_cell::{EmptyPlotCell, PlantCell};
pub use product_detail_modal::{ProductDetailModal, ProductDetailModalProps};
pub use set_card::{render_uniform_set_card, SetCardData};
pub use strain_card::{StrainCard, StrainCardProps};
pub use strain_grid::{StrainGrid, StrainGridProps};
pub use video_modal::{VideoModal, VideoModalProps};

// ---------------------------------------------------------------------------
// Re-exports — new design-system components
// ---------------------------------------------------------------------------
pub use badge::{Badge, BadgeProps, BadgeSize, BadgeVariant};
pub use chip::{Chip, ChipColor, ChipGroup, ChipGroupProps, ChipProps};
pub use empty_state::{EmptyState, EmptyStateProps};
pub use error_banner::{ErrorBanner, ErrorBannerProps};
pub use error_overlay::{install_error_handlers, ErrorOverlay, JsErrorItem};
pub use id_picker::{IdPicker, IdPickerProps};
pub use lazy_screen::LazyScreen;
pub use progress_bar::{ProgressBar, ProgressBarProps, ProgressColor, ProgressSize};
pub use rarity_glow::{Rarity, RarityGlow, RarityGlowProps};
pub use skeleton::{Skeleton, SkeletonProps, SkeletonRow, SkeletonRowProps, SkeletonShape};
pub use toast::{Toast, ToastContainer, ToastContainerProps, ToastKind, ToastProps};

// Re-export types from state for convenience
pub use crate::ui::state::CartItem as CartItemType;
