#!/bin/bash
# Generate all atomic component pages from ui-kit.html sections
set -euo pipefail

DIR="$(cd "$(dirname "$0")" && pwd)"
ROOT="$(cd "$DIR/.." && pwd)"
UKIT="$ROOT/ui-kit.html"

# Common CSS
CSS=':root{--bg:#0f0f1a;--bg2:#1a1a2e;--card:#16213e;--border:#2a2a4a;--text:#e8e8e8;--text2:#8b8b9e;--green:#39ff14;--cyan:#00e5ff;--yellow:#ffe600;--purple:#b388ff;--red:#ff4757;--orange:#ff9f43;--pixel-shadow:4px 4px 0 rgba(0,0,0,0.5);--radius-sm:4px;--radius-md:8px;--radius-lg:12px;}*{box-sizing:border-box;margin:0;padding:0;}body{font-family:Inter,-apple-system,sans-serif;background:var(--bg);color:var(--text);padding:24px;max-width:600px;margin:0 auto;}h1{font-family:"Press Start 2P",monospace;font-size:10px;color:var(--cyan);margin-bottom:20px;text-transform:uppercase;letter-spacing:2px;}'

# 05-bike-cards
cat > "$DIR/05-bike-cards/index.html" << 'HTMLEOF'
<!DOCTYPE html><html><head><meta charset="utf-8"/><meta name="viewport" content="width=device-width,initial-scale=1.0"/><title>05 · Bike Cards</title>
<link href="https://fonts.googleapis.com/css2?family=Inter:wght@400;600;700&family=Press+Start+2P&display=swap" rel="stylesheet">
<style>:root{--bg:#0f0f1a;--bg2:#1a1a2e;--card:#16213e;--border:#2a2a4a;--text:#e8e8e8;--text2:#8b8b9e;--green:#39ff14;--cyan:#00e5ff;--yellow:#ffe600;--purple:#b388ff;--red:#ff4757;--pixel-shadow:4px 4px 0 rgba(0,0,0,0.5);--radius-sm:4px;--radius-md:8px;}*{box-sizing:border-box;margin:0;padding:0;}body{font-family:'Inter',sans-serif;background:var(--bg);color:var(--text);padding:24px;}h1{font-family:'Press Start 2P',monospace;font-size:10px;color:var(--cyan);margin-bottom:20px;text-transform:uppercase;letter-spacing:2px;}.note{font-size:10px;color:var(--text2);margin-bottom:12px;}.grid{display:grid;grid-template-columns:1fr 1fr;gap:12px;}.card{background:var(--card);border:2px solid var(--border);border-radius:var(--radius-md);overflow:hidden;box-shadow:var(--pixel-shadow);}.card.pick{border-color:var(--yellow);}.card.unavailable{opacity:0.6;}.img{height:100px;background:linear-gradient(135deg,var(--bg2),var(--card));display:flex;align-items:center;justify-content:center;font-size:40px;position:relative;}.pick-badge{position:absolute;top:6px;right:6px;font-family:'Press Start 2P',monospace;font-size:6px;background:var(--yellow);color:#000;padding:2px 5px;border-radius:var(--radius-sm);}.content{padding:10px;}.name{font-size:13px;font-weight:700;margin-bottom:4px;}.type{display:flex;gap:4px;align-items:center;margin-bottom:4px;}.badge{font-family:'Press Start 2P',monospace;font-size:6px;padding:2px 5px;border-radius:var(--radius-sm);border:1px solid;}.b-motorcycle{color:var(--cyan);border-color:var(--cyan);background:rgba(0,229,255,0.1);}.b-scooter{color:var(--green);border-color:var(--green);background:rgba(57,255,20,0.1);}.cc{font-size:10px;color:var(--text2);}.desc{font-size:10px;color:var(--text2);margin-bottom:6px;}.price{font-family:'Press Start 2P',monospace;font-size:10px;color:var(--green);}.actions{padding:0 10px 10px;}.btn{font-family:'Press Start 2P',monospace;border:2px solid var(--border);padding:6px 12px;font-size:7px;cursor:pointer;box-shadow:var(--pixel-shadow);border-radius:var(--radius-sm);width:100%;text-transform:uppercase;}.btn-primary{background:var(--green);color:#000;border-color:var(--green);}.btn-ghost{background:transparent;color:var(--text2);border-color:var(--text2);}.btn:disabled{opacity:0.4;cursor:not-allowed;}</style></head><body>
<h1>05 · Bike Cards</h1>
<p class="note">Sample data from data/fleet_seed.json (measured 2026-09-12): models, units free and the published base day tariff, before the class discount. A family with no published tariff shows a dash.</p>
<div class="grid">
<div class="card"><div class="img">🛵</div><div class="content"><div class="name">Yamaha NMAX 155</div><div class="type"><span class="badge b-scooter">🛵 Scooter</span><span class="cc">155 cc</span></div><div class="desc">Available: 5</div><div class="price">฿449/day</div></div><div class="actions"><button class="btn btn-primary">Add to Cart 🛒</button></div></div>
<div class="card pick"><div class="img">🛵<span class="pick-badge">PICK</span></div><div class="content"><div class="name">Honda ADV 350</div><div class="type"><span class="badge b-scooter">🛵 Scooter</span><span class="cc">350 cc</span></div><div class="desc">Available: 5</div><div class="price">฿998/day</div></div><div class="actions"><button class="btn btn-primary">Add to Cart 🛒</button></div></div>
<div class="card"><div class="img">🏍️</div><div class="content"><div class="name">Honda CB650R</div><div class="type"><span class="badge b-motorcycle">🏍️ Motorcycle</span><span class="cc">650 cc</span></div><div class="desc">Available: 1</div><div class="price">฿1,798/day</div></div><div class="actions"><button class="btn btn-primary">Add to Cart 🛒</button></div></div>
<div class="card unavailable"><div class="img" style="opacity:0.5;">🛵</div><div class="content"><div class="name">Honda Click 125</div><div class="type"><span class="badge b-scooter">🛵 Scooter</span><span class="cc">125 cc</span></div><div class="desc">Not rented at the moment</div><div class="price" style="color:var(--text2);">—</div></div><div class="actions"><button class="btn btn-ghost" disabled>Sold Out</button></div></div>
</div></body></html>
HTMLEOF

# 06-order-cards
cat > "$DIR/06-order-cards/index.html" << 'HTMLEOF'
<!DOCTYPE html><html><head><meta charset="utf-8"/><meta name="viewport" content="width=device-width,initial-scale=1.0"/><title>06 · Order Cards</title>
<link href="https://fonts.googleapis.com/css2?family=Inter:wght@400;600;700&family=Press+Start+2P&display=swap" rel="stylesheet">
<style>:root{--bg:#0f0f1a;--bg2:#1a1a2e;--card:#16213e;--border:#2a2a4a;--text:#e8e8e8;--text2:#8b8b9e;--green:#39ff14;--cyan:#00e5ff;--yellow:#ffe600;--purple:#b388ff;--red:#ff4757;--pixel-shadow:4px 4px 0 rgba(0,0,0,0.5);--radius-sm:4px;--radius-md:8px;}*{box-sizing:border-box;margin:0;padding:0;}body{font-family:'Inter',sans-serif;background:var(--bg);color:var(--text);padding:24px;}h1{font-family:'Press Start 2P',monospace;font-size:10px;color:var(--cyan);margin-bottom:20px;text-transform:uppercase;letter-spacing:2px;}.note{font-size:10px;color:var(--text2);margin-bottom:12px;}.order{background:var(--card);border:2px solid var(--border);border-radius:var(--radius-md);padding:14px;box-shadow:var(--pixel-shadow);margin-bottom:10px;}.header{display:flex;justify-content:space-between;align-items:center;margin-bottom:6px;}.id{font-weight:700;font-size:12px;}.status{font-family:'Press Start 2P',monospace;font-size:7px;padding:3px 7px;border-radius:var(--radius-sm);text-transform:uppercase;}.s-pending{color:var(--yellow);background:rgba(255,230,0,0.1);border:1px solid var(--yellow);}.s-delivered{color:var(--green);background:rgba(57,255,20,0.1);border:1px solid var(--green);}.s-processing{color:var(--cyan);background:rgba(0,229,255,0.1);border:1px solid var(--cyan);}.body{font-size:12px;color:var(--text2);}.footer{display:flex;justify-content:space-between;align-items:center;margin-top:6px;padding-top:6px;border-top:1px solid var(--border);}.total{font-family:'Press Start 2P',monospace;font-size:9px;color:var(--green);}.date{font-size:10px;color:var(--text2);}</style></head><body>
<h1>06 · Order Cards</h1>
<p class="note">Sample orders with models from data/fleet_seed.json. No total is computed here, so each shows a dash.</p>
<div class="order"><div class="header"><span class="id">Order #...a1b2c3d4</span><span class="status s-pending">Pending</span></div><div class="body">Yamaha NMAX 155 x1, Honda ADV 350 x1</div><div class="footer"><span class="total">—</span><span class="date">2026-05-02</span></div></div>
<div class="order"><div class="header"><span class="id">Order #...e5f6g7h8</span><span class="status s-delivered">Delivered</span></div><div class="body">Yamaha XMAX 300 x1</div><div class="footer"><span class="total">—</span><span class="date">2026-04-28</span></div></div>
<div class="order"><div class="header"><span class="id">Order #...i9j0k1l2</span><span class="status s-processing">Processing</span></div><div class="body">Honda CB650R x1</div><div class="footer"><span class="total">—</span><span class="date">2026-05-01</span></div></div>
</body></html>
HTMLEOF

# 07-cart
cat > "$DIR/07-cart/index.html" << 'HTMLEOF'
<!DOCTYPE html><html><head><meta charset="utf-8"/><meta name="viewport" content="width=device-width,initial-scale=1.0"/><title>07 · Cart</title>
<link href="https://fonts.googleapis.com/css2?family=Inter:wght@400;600;700&family=Press+Start+2P&display=swap" rel="stylesheet">
<style>:root{--bg:#0f0f1a;--bg2:#1a1a2e;--card:#16213e;--border:#2a2a4a;--text:#e8e8e8;--text2:#8b8b9e;--green:#39ff14;--pixel-shadow:4px 4px 0 rgba(0,0,0,0.5);--radius-sm:4px;--radius-md:8px;}*{box-sizing:border-box;margin:0;padding:0;}body{font-family:'Inter',sans-serif;background:var(--bg);color:var(--text);padding:24px;}h1{font-family:'Press Start 2P',monospace;font-size:10px;color:var(--cyan);margin-bottom:20px;text-transform:uppercase;letter-spacing:2px;}.note{font-size:10px;color:var(--text2);margin-bottom:12px;}.item{display:flex;align-items:center;gap:10px;background:var(--card);border:2px solid var(--border);border-radius:var(--radius-md);padding:10px;margin-bottom:8px;box-shadow:var(--pixel-shadow);}.img{width:44px;height:44px;background:var(--bg2);border-radius:var(--radius-sm);display:flex;align-items:center;justify-content:center;font-size:22px;flex-shrink:0;}.info{flex:1;}.name{font-weight:600;font-size:12px;}.price{font-size:10px;color:var(--text2);}.controls{display:flex;align-items:center;gap:6px;}.qty{width:26px;height:26px;border:2px solid var(--border);background:var(--bg2);color:var(--text);border-radius:var(--radius-sm);cursor:pointer;font-size:14px;display:flex;align-items:center;justify-content:center;}.val{font-family:'Press Start 2P',monospace;font-size:9px;min-width:18px;text-align:center;}.summary{background:var(--card);border:2px solid var(--border);border-radius:var(--radius-md);padding:14px;box-shadow:var(--pixel-shadow);}.row{display:flex;justify-content:space-between;margin-bottom:6px;font-size:12px;}.row.total{font-weight:700;padding-top:6px;border-top:1px solid var(--border);margin-top:6px;}.amount{font-family:'Press Start 2P',monospace;font-size:12px;color:var(--green);}</style></head><body>
<h1>07 · Cart</h1>
<p class="note">Sample cart: models and published base day tariffs, before the class discount, from data/fleet_seed.json. No subtotal or total is computed here, and the seed publishes a delivery price for Bangtao only, so each of the three shows a dash.</p>
<div class="item"><div class="img">🛵</div><div class="info"><div class="name">Yamaha NMAX 155</div><div class="price">฿449/day</div></div><div class="controls"><button class="qty">−</button><span class="val">1</span><button class="qty">+</button></div></div>
<div class="item"><div class="img">🏍️</div><div class="info"><div class="name">Honda CB650R</div><div class="price">฿1,798/day</div></div><div class="controls"><button class="qty">−</button><span class="val">1</span><button class="qty">+</button></div></div>
<div class="summary"><div class="row"><span style="color:var(--text2)">Subtotal:</span><span>—</span></div><div class="row"><span style="color:var(--text2)">Delivery:</span><span>—</span></div><div class="row total"><span>Total:</span><span class="amount">—</span></div></div>
</body></html>
HTMLEOF

echo "Generated: 05-bike-cards, 06-order-cards, 07-cart"
